# Generated by Django 4.1 on 2023-03-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bundle_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
