# Generated by Django 4.1 on 2023-03-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares_app', '0002_customuser_bundle_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
