# Generated by Django 4.1 on 2023-03-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares_app', '0004_remove_customuser_bundle_amount_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bundle_amount',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bundle_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
