# Generated by Django 4.1 on 2023-03-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares_app', '0005_remove_userprofile_bundle_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bundle_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
