# Generated by Django 4.1 on 2023-03-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares_app', '0007_transactionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bundle_amount',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(default='Business', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_sender_name',
            field=models.CharField(default='Bundle', max_length=100),
        ),
    ]
