# Generated by Django 4.1 on 2023-03-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares_app', '0009_remove_customuser_name_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='batch_id',
            field=models.CharField(default='Failed', max_length=100),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='reference',
            field=models.CharField(default='Failed', max_length=100),
        ),
    ]
