# Generated by Django 4.1 on 2023-03-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares_app', '0010_transactionhistory_batch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('code_status', models.BooleanField()),
            ],
        ),
    ]
