# Generated by Django 4.1.3 on 2023-05-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares_app', '0011_authorizationcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='api_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='api_secret',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
