# Generated by Django 4.1.3 on 2023-05-19 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares_app', '0012_customuser_api_key_customuser_api_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('account_email', models.EmailField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('reference', models.CharField(default='Failed', max_length=100)),
                ('bundle_amount', models.FloatField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_status', models.CharField(max_length=100)),
                ('batch_id', models.CharField(default='Failed', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
