# Generated by Django 4.1.3 on 2023-05-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares_app', '0014_alter_newtransaction_reference_creditinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtransaction',
            name='reference',
            field=models.CharField(default='Failed', max_length=100),
        ),
    ]
