# Generated by Django 4.1.3 on 2023-05-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares_app', '0015_alter_newtransaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='api_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newtransaction',
            name='transaction_status',
            field=models.CharField(default='Failed', max_length=100),
        ),
    ]
