# Generated by Django 4.2.4 on 2023-12-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares_app', '0017_delete_transactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sms_api',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
